# Generated by Django 2.2.7 on 2019-11-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRentalCollectionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_person_collecting', models.CharField(max_length=60)),
                ('collection_address', models.CharField(max_length=60)),
                ('force_number', models.FloatField(max_length=40)),
                ('telephone', models.IntegerField(max_length=20)),
                ('collection_post_code', models.CharField(max_length=30)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
