# Generated by Django 2.2.7 on 2019-11-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_rental_collection_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclerentalcollectiondetails',
            name='telephone',
            field=models.IntegerField(),
        ),
    ]
