# Generated by Django 2.2.7 on 2019-12-01 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleHire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_hire_rental_code', models.CharField(max_length=60)),
                ('vehicle_hire_registration_number', models.FloatField(max_length=60)),
                ('vehicle_hire_extra_registration_number', models.FloatField(max_length=60)),
                ('vehicle_hire_replaced_plate', models.FloatField(max_length=60)),
                ('vehicle_hire_replaced_plate_cost_center', models.CharField(max_length=100)),
                ('vehicle_hire_temprature_contract_end_date', models.DateField(auto_now_add=True)),
                ('vehicle_hire_start_date', models.DateField(auto_now_add=True)),
                ('vehicle_hire_end_date', models.DateField(auto_now_add=True)),
                ('vehicle_hire_start_time', models.TimeField(auto_now_add=True)),
                ('vehicle_hire_end_time', models.TimeField(auto_now_add=True)),
                ('vehicle_hire_odometer_in', models.FloatField()),
                ('vehicle_hire_odometer_out', models.FloatField()),
                ('vehicle_hire_on_hire_reference', models.CharField(max_length=100)),
                ('vehicle_hire_off_hire_reference', models.CharField(max_length=100)),
                ('vehicle_hire_days', models.DateField(auto_now_add=True)),
                ('vehicle_hire_distance', models.FloatField()),
                ('vehicle_hire_comments', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleHireCostCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_hire_cost_center', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleHireReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_hire_reason', models.CharField(max_length=300)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleHireRentalDetailHiringDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_rental_detail_hiring_division', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleHireRentalInvoicesTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_rental_invoices_to', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleHireRentalPaymentRecieved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_recieved', models.FloatField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleHireRentalPaymentRecievedBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_rental_payment_recieved', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleHireRentalPaymentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_rental_payment_status', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleHireRentalRevenueInvoicedBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_rental_revenue_invoiced_by', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleHireRentalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_hire_rental_status', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleHireStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_hire_status', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleHireRentalRevenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_amount', models.FloatField()),
                ('payment_details', models.CharField(max_length=100)),
                ('date_assurance_authorized', models.DateField(auto_now_add=True)),
                ('vehicle_insurance_days_off', models.DateField(auto_now_add=True)),
                ('invoice_number', models.IntegerField()),
                ('insurance_payment_days', models.DateField(auto_now_add=True)),
                ('date_inv_prepared', models.DateField(auto_now_add=True)),
                ('date_insurance_benefits_end', models.DateField(auto_now_add=True)),
                ('daily_rental_charge', models.FloatField()),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('insurance_non_payment_days', models.DateField(auto_now_add=True)),
                ('payment_recieved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_hire.VehicleHireRentalPaymentRecieved')),
                ('vehicle_hire_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_hire.VehicleHire')),
                ('vehicle_rental_invoices_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_hire.VehicleHireRentalInvoicesTo')),
                ('vehicle_rental_payment_recieved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_hire.VehicleHireRentalPaymentRecievedBy')),
                ('vehicle_rental_payment_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_hire.VehicleHireRentalPaymentStatus')),
                ('vehicle_rental_revenue_invoiced_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_hire.VehicleHireRentalRevenueInvoicedBy')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleHireRentalCollectionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_person_collecting', models.CharField(max_length=60)),
                ('collection_address', models.CharField(max_length=60)),
                ('force_number', models.FloatField(max_length=40)),
                ('telephone', models.IntegerField()),
                ('collection_post_code', models.CharField(max_length=30)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('hiring_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_hire.VehicleHireRentalDetailHiringDivision')),
                ('vehicle_hire_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_hire.VehicleHire')),
            ],
        ),
        migrations.AddField(
            model_name='vehiclehire',
            name='vehicle_hire_cost_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_hire.VehicleHireCostCenter'),
        ),
        migrations.AddField(
            model_name='vehiclehire',
            name='vehicle_hire_reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_hire.VehicleHireReason'),
        ),
        migrations.AddField(
            model_name='vehiclehire',
            name='vehicle_hire_rental_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_hire.VehicleHireRentalStatus'),
        ),
        migrations.AddField(
            model_name='vehiclehire',
            name='vehicle_hire_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_hire.VehicleHireStatus'),
        ),
    ]
