# Generated by Django 2.2.7 on 2019-12-01 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepairInvoicedTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_invoiced_to_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepairInvoicePaid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_invoice_paid_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepairInvoiceRecieved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_invoice_recieved_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepairJobStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_job_status_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepairPaperworkStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_paperwork_status_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepairReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_reason_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepairRecharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_recharge_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepairRecievedBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_recieved_by_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepairSupply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_supply_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepairWorkshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_workshop_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(max_length=60)),
                ('extra_registration_no', models.CharField(max_length=60)),
                ('year', models.CharField(max_length=60)),
                ('fleet_number', models.CharField(max_length=60)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('date_returned_to_workshop', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleBodyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCompanyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleConventionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convention_type_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCostCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_center_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCounty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCurrencyCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_codes_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDeductability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deductability_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleFuelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleGearBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gear_box_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleInPull',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_pull_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleInsuranceCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_company_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleLocationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_code_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleMakeCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_code_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModelCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_code_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleReturnedWorkshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_workshop_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleTyre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tyre_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_odometer', models.CharField(max_length=250)),
                ('next_service', models.CharField(max_length=60)),
                ('next_inspection', models.CharField(max_length=60)),
                ('l_per_km', models.CharField(max_length=60)),
                ('cost_per_km', models.CharField(max_length=60)),
                ('total_cost', models.CharField(max_length=60)),
                ('number_of_remining_tyres', models.CharField(max_length=60)),
                ('cumilative_balance', models.CharField(max_length=60)),
                ('in_pull_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleInPull')),
                ('location_code_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleLocationCode')),
                ('vehicle_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleCountry')),
                ('vehicle_currency_codes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleCurrencyCodes')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleRepair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_authorization_no', models.CharField(max_length=60)),
                ('created_by', models.CharField(max_length=60)),
                ('registration_no', models.CharField(max_length=60)),
                ('sales_outlet', models.CharField(max_length=60)),
                ('insurance_company', models.CharField(max_length=60)),
                ('alias_plate_number', models.CharField(max_length=60)),
                ('sap_account_number', models.CharField(max_length=60)),
                ('cumilative_balance', models.CharField(max_length=60)),
                ('repair_supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.RepairSupply')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=60)),
                ('contract_baloon_payment', models.CharField(max_length=60)),
                ('notes', models.CharField(max_length=60)),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waranty', models.CharField(max_length=60)),
                ('waranty_distance', models.CharField(max_length=60)),
                ('insurance_expiry', models.CharField(max_length=60)),
                ('insurance_commencement', models.CharField(max_length=60)),
                ('motor_insurance_policy_no', models.CharField(max_length=60)),
                ('mid_on', models.CharField(max_length=60)),
                ('mid_off', models.CharField(max_length=60)),
                ('insurance_certificate', models.CharField(max_length=60)),
                ('service_date', models.CharField(max_length=60)),
                ('last_service_type', models.CharField(max_length=60)),
                ('service_schedule', models.CharField(max_length=60)),
                ('service_interval_weeks', models.CharField(max_length=60)),
                ('service_interval_kms', models.CharField(max_length=60)),
                ('inspection_date', models.CharField(max_length=60)),
                ('inspection_type', models.CharField(max_length=60)),
                ('inspection_interval_weeks', models.CharField(max_length=60)),
                ('inspection_interval_distance', models.CharField(max_length=60)),
                ('inspection_certificate_no', models.CharField(max_length=60)),
                ('distance_per_year', models.CharField(max_length=60)),
                ('distance_per_day', models.CharField(max_length=60)),
                ('age_years', models.CharField(max_length=60)),
                ('age_days', models.CharField(max_length=60)),
                ('deviation', models.CharField(max_length=60)),
                ('deviation_perc', models.CharField(max_length=60)),
                ('odometer', models.CharField(max_length=60)),
                ('current_odo_date', models.CharField(max_length=60)),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle')),
                ('vehicle_insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleInsuranceCompany')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exterior_color', models.CharField(max_length=60)),
                ('ecoscore', models.CharField(max_length=60)),
                ('interior_color', models.CharField(max_length=60)),
                ('number_of_doors', models.CharField(max_length=60)),
                ('co2km', models.CharField(max_length=60)),
                ('key_number', models.CharField(max_length=60)),
                ('chassis_number', models.CharField(max_length=60)),
                ('fiscal_hp', models.CharField(max_length=60)),
                ('engiene_number', models.CharField(max_length=60)),
                ('engiene_cc', models.CharField(max_length=60)),
                ('distance_to_work', models.CharField(max_length=60)),
                ('vehicle_phone_number', models.CharField(max_length=60)),
                ('bhp', models.CharField(max_length=60)),
                ('gross_vehicle_weight', models.CharField(max_length=60)),
                ('winter_tyres', models.CharField(max_length=60)),
                ('winter_tyres_location', models.CharField(max_length=60)),
                ('tank_size', models.CharField(max_length=60)),
                ('vehicle_deductability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleDeductability')),
                ('vehicle_gear_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleGearBox')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(max_length=60)),
                ('extra_registration_no', models.CharField(max_length=60)),
                ('asset_description', models.CharField(max_length=60)),
                ('asset_type', models.CharField(max_length=60)),
                ('asset_make', models.CharField(max_length=60)),
                ('asset_model', models.CharField(max_length=60)),
                ('asset_issue_date', models.CharField(max_length=60)),
                ('asset_return_date', models.CharField(max_length=60)),
                ('asset_serial', models.CharField(max_length=60)),
                ('driver_name', models.CharField(max_length=60)),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=60)),
                ('registratyion_no', models.CharField(max_length=60)),
                ('changed_by', models.CharField(max_length=60)),
                ('date', models.CharField(max_length=60)),
                ('company_code', models.CharField(max_length=60)),
                ('cost_center', models.CharField(max_length=60)),
                ('start_date', models.CharField(max_length=60)),
                ('odometer', models.CharField(max_length=60)),
                ('end_date', models.CharField(max_length=60)),
                ('end_odometer', models.CharField(max_length=60)),
                ('lock', models.CharField(max_length=60)),
                ('workshop', models.CharField(max_length=60)),
                ('allocation_reason', models.CharField(max_length=60)),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_body_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleBodyType'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleClient'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_company_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleCompanyCode'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_convention_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleConventionType'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_cost_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleCostCenter'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleCounty'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_fuel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleFuelType'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_location_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleLocationCode'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_make_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleMakeCode'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_model_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleModelCode'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_returned_workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleReturnedWorkshop'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleStatus'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_tyre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleTyre'),
        ),
        migrations.CreateModel(
            name='RepairServiceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_authorization_no', models.CharField(max_length=60)),
                ('workshop', models.CharField(max_length=60)),
                ('job_status', models.CharField(max_length=60)),
                ('registration_no', models.CharField(max_length=60)),
                ('extra_registration_no', models.CharField(max_length=60)),
                ('model_code', models.CharField(max_length=60)),
                ('division_code', models.CharField(max_length=60)),
                ('cost_center', models.CharField(max_length=60)),
                ('odometer_in', models.CharField(max_length=60)),
                ('reason', models.CharField(max_length=60)),
                ('job_date', models.CharField(max_length=60)),
                ('job_end_date', models.CharField(max_length=60)),
                ('invoice', models.CharField(max_length=60)),
                ('total_invoice', models.CharField(max_length=60)),
                ('comments', models.CharField(max_length=60)),
                ('repair_paperwork_status', models.CharField(max_length=60)),
                ('cost_labour', models.CharField(max_length=60)),
                ('created_by', models.CharField(max_length=60)),
                ('changed_by', models.CharField(max_length=60)),
                ('date', models.CharField(max_length=60)),
                ('repair_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='RepairInvoiceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.CharField(max_length=60)),
                ('invoice_no', models.CharField(max_length=60)),
                ('invoice_recieved_date', models.CharField(max_length=60)),
                ('invoice_parts', models.CharField(max_length=60)),
                ('invoice_labour', models.CharField(max_length=60)),
                ('total_invoice', models.CharField(max_length=60)),
                ('invoice_comment', models.CharField(max_length=60)),
                ('total_tax', models.CharField(max_length=60)),
                ('location_code', models.CharField(max_length=60)),
                ('total_gross', models.CharField(max_length=60)),
                ('repair_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle')),
                ('repair_invoiced_paid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.RepairInvoicePaid')),
                ('repair_invoiced_recieved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.RepairInvoiceRecieved')),
                ('repair_invoiced_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.RepairInvoicedTo')),
                ('repair_recharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.RepairRecharge')),
                ('repair_recieved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.RepairRecievedBy')),
            ],
        ),
        migrations.CreateModel(
            name='RepairEstimationCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_labour_cost', models.CharField(max_length=60)),
                ('actual_parts_cost', models.CharField(max_length=60)),
                ('actual_tax_cost', models.CharField(max_length=60)),
                ('estimated_hours', models.CharField(max_length=60)),
                ('actual_total_gross', models.CharField(max_length=60)),
                ('actual_total_net', models.CharField(max_length=60)),
                ('repair_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='RepairDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_client', models.CharField(max_length=60)),
                ('service_type', models.CharField(max_length=60)),
                ('job_date', models.CharField(max_length=60)),
                ('job_end_date', models.CharField(max_length=60)),
                ('odometer_in', models.CharField(max_length=60)),
                ('odometer_out', models.CharField(max_length=60)),
                ('days_off_road', models.CharField(max_length=60)),
                ('cost_center', models.CharField(max_length=60)),
                ('service_advice', models.CharField(max_length=60)),
                ('cost_parts', models.CharField(max_length=60)),
                ('cost_labour', models.CharField(max_length=60)),
                ('cost_total_net', models.CharField(max_length=60)),
                ('comments', models.CharField(max_length=60)),
                ('repair_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle')),
                ('repair_job_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.RepairJobStatus')),
                ('repair_paperwork_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.RepairPaperworkStatus')),
                ('repair_reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.RepairReason')),
                ('repair_workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.RepairWorkshop')),
            ],
        ),
    ]
