# Generated by Django 2.2.7 on 2019-11-29 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle_tyre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(max_length=60)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('vehicle_tyre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_tyre.VehicleTyre')),
            ],
        ),
    ]
