# Generated by Django 2.1.2 on 2019-11-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=60)),
                ('vehicle_model', models.CharField(max_length=60)),
                ('vehicle_make', models.CharField(max_length=60)),
                ('vehcile_type', models.CharField(max_length=60)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
