# Generated by Django 2.1.2 on 2019-11-28 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehcile_type',
            new_name='vehicle_type',
        ),
    ]
