# Generated by Django 2.2.7 on 2019-12-01 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accident_status_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccidentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accident_type_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrokersName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brokers_name_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimFormRecieved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_form_recieved_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimInspectionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_inspection_report_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimPoliceAbstract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_police_abstract_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimRepairEstimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_repair_estimate_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_center_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DamageToVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_to_vehicle_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoorsLocked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doors_locked_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriverLicenseRecieved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_license_recieved_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntryGained',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_gained_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiabilityFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liability_flag_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherVehicleInvolved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_vehicle_involved_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartyToBlame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_to_blame_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoadConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_conditions_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoadType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_type_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdPartiesInvolved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('third_parties_involved_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfLossClaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_loss_claim_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleBroken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_broken_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleRecovered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_recovered_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WriteOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('write_off_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleAccident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accident_ref', models.CharField(max_length=60)),
                ('date', models.CharField(max_length=60)),
                ('claim_handler', models.CharField(max_length=60)),
                ('created_by', models.CharField(max_length=60)),
                ('accident_report_from_recieved', models.CharField(max_length=60)),
                ('date_claim_completed', models.CharField(max_length=60)),
                ('date_insurers_notified', models.CharField(max_length=60)),
                ('insurance_reference', models.CharField(max_length=60)),
                ('broker_reference', models.CharField(max_length=60)),
                ('accident_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.AccidentStatus')),
                ('accident_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.AccidentType')),
                ('brokers_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.BrokersName')),
                ('company_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.CompanyCode')),
                ('liability_flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.LiabilityFlag')),
                ('party_to_blame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.PartyToBlame')),
                ('type_of_loss_claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.TypeOfLossClaim')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='AccidentVor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accident_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle')),
                ('write_off', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.WriteOff')),
            ],
        ),
        migrations.CreateModel(
            name='AccidentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accident_ref', models.CharField(max_length=60)),
                ('item_number', models.CharField(max_length=60)),
                ('accident_date', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('Telephone', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('tp_insur_comp', models.CharField(max_length=60)),
                ('tp_insur_comp_address', models.CharField(max_length=60)),
                ('tp_insur_comp_telephone', models.CharField(max_length=60)),
                ('tp_policy', models.CharField(max_length=60)),
                ('tp_dem_desc', models.CharField(max_length=60)),
                ('tp_veh', models.CharField(max_length=60)),
                ('exterior_color', models.CharField(max_length=60)),
                ('third_party_registration_no', models.CharField(max_length=60)),
                ('accident_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle')),
                ('third_parties_involved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.ThirdPartiesInvolved')),
            ],
        ),
        migrations.CreateModel(
            name='AccidentDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accident_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle')),
                ('claim_form_recieved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.ClaimFormRecieved')),
                ('claim_inspection_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.ClaimInspectionReport')),
                ('claim_police_abstract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.ClaimPoliceAbstract')),
                ('claim_repair_estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.ClaimRepairEstimate')),
                ('driver_license_recieved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.DriverLicenseRecieved')),
            ],
        ),
        migrations.CreateModel(
            name='AccidentCosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_accident_damage', models.CharField(max_length=60)),
                ('estimated_towing_costs', models.CharField(max_length=60)),
                ('estimated_associated_costs', models.CharField(max_length=60)),
                ('estimated_suplimentary_costs', models.CharField(max_length=60)),
                ('estimated_wild_screen_glass_costs', models.CharField(max_length=60)),
                ('estimated_total_costs', models.CharField(max_length=60)),
                ('actual_accident_damage', models.CharField(max_length=60)),
                ('actual_towing_costs', models.CharField(max_length=60)),
                ('actual_associated_costs', models.CharField(max_length=60)),
                ('actual_suplimentary_costs', models.CharField(max_length=60)),
                ('actual_wild_screen_glass_costs', models.CharField(max_length=60)),
                ('actual_total_costs', models.CharField(max_length=60)),
                ('accident_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='AccidentBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=60)),
                ('date_of_birth', models.CharField(max_length=60)),
                ('force_number', models.CharField(max_length=60)),
                ('registration_no', models.CharField(max_length=60)),
                ('extra_registration_no', models.CharField(max_length=60)),
                ('make_code', models.CharField(max_length=60)),
                ('model_code', models.CharField(max_length=60)),
                ('client_division', models.CharField(max_length=60)),
                ('engiene_cc', models.CharField(max_length=60)),
                ('fuel_type', models.CharField(max_length=60)),
                ('insurance_company', models.CharField(max_length=60)),
                ('owner', models.CharField(max_length=60)),
                ('pending_convictions', models.CharField(max_length=60)),
                ('towing_company', models.CharField(max_length=60)),
                ('towing_from', models.CharField(max_length=60)),
                ('towing_to', models.CharField(max_length=60)),
                ('contact_person', models.CharField(max_length=60)),
                ('phone_number', models.CharField(max_length=60)),
                ('towing_date', models.CharField(max_length=60)),
                ('your_vehicle_light', models.CharField(max_length=60)),
                ('your_vehicle_signaling', models.CharField(max_length=60)),
                ('other_vehicle_light', models.CharField(max_length=60)),
                ('other_vehicle_signaling', models.CharField(max_length=60)),
                ('accident_date', models.CharField(max_length=60)),
                ('exact_time_of_incident', models.CharField(max_length=60)),
                ('exact_time_of_accident', models.CharField(max_length=60)),
                ('comment', models.CharField(max_length=60)),
                ('incident_time_range', models.CharField(max_length=60)),
                ('use_of_vehicle_at_time_of_incident', models.CharField(max_length=60)),
                ('current_location_of_vehicle', models.CharField(max_length=60)),
                ('vehicle_defect_damage', models.CharField(max_length=60)),
                ('accident_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.CostCenter')),
                ('damage_to_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.DamageToVehicle')),
                ('doors_locked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.DoorsLocked')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Driver')),
                ('entry_gained', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.EntryGained')),
                ('other_vehicle_involved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.OtherVehicleInvolved')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Relationship')),
                ('road_conditions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.RoadConditions')),
                ('road_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.RoadType')),
                ('vehicle_broken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleBroken')),
                ('vehicle_recovered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleRecovered')),
                ('weather', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Weather')),
            ],
        ),
    ]
