# Generated by Django 2.2.7 on 2019-12-01 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepairSupply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_supply_name', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='vehiclediary',
            name='repair_supply',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='vehicle.RepairSupply'),
            preserve_default=False,
        ),
    ]
