# Generated by Django 2.2.7 on 2019-11-30 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_auto_20191130_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='bhp',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='chassis_number',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='co2km',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='distance_to_work',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='ecoscore',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='engiene_cc',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='engiene_number',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='exterior_color',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='fiscal_hp',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='gross_vehicle_weight',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='interior_color',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='key_number',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='number_of_doors',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='tank_size',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_deductability',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_gear_box',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_phone_number',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='winter_tyres',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='winter_tyres_location',
        ),
        migrations.CreateModel(
            name='VehicleBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exterior_color', models.CharField(max_length=60)),
                ('ecoscore', models.CharField(max_length=60)),
                ('interior_color', models.CharField(max_length=60)),
                ('number_of_doors', models.CharField(max_length=60)),
                ('co2km', models.CharField(max_length=60)),
                ('key_number', models.CharField(max_length=60)),
                ('chassis_number', models.CharField(max_length=60)),
                ('fiscal_hp', models.CharField(max_length=60)),
                ('engiene_number', models.CharField(max_length=60)),
                ('engiene_cc', models.CharField(max_length=60)),
                ('distance_to_work', models.CharField(max_length=60)),
                ('vehicle_phone_number', models.CharField(max_length=60)),
                ('bhp', models.CharField(max_length=60)),
                ('gross_vehicle_weight', models.CharField(max_length=60)),
                ('winter_tyres', models.CharField(max_length=60)),
                ('winter_tyres_location', models.CharField(max_length=60)),
                ('tank_size', models.CharField(max_length=60)),
                ('vehicle_deductability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleDeductability')),
                ('vehicle_gear_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleGearBox')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle')),
            ],
        ),
    ]
